### ISSUE TITLE
Failure to build for ESP32 due to lack of SoftwareSerial

### ISSUE THREAD

**Issue by davefiddes** [gicking/LIN_master_portable_Arduino#1]
Trying to build `LIN_master_portable/examples/LIN_HardwareSerial_ESP32_Background/LIN_HardwareSerial_ESP32_Background.ino` fails with:

```text
In file included from /home/dave/Arduino/libraries/LIN_master_portable/src/LIN_master_SoftwareSerial.cpp:14:
/home/dave/Arduino/libraries/LIN_master_portable/src/LIN_master_SoftwareSerial.h:25:10: fatal error: SoftwareSerial.h: No such file or directory
 #include <SoftwareSerial.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

This is with esp32-arduino 2.0.9 release. I've checked back to the 2.0.0 and 1.0.6 releases and it doesn't appear to work there either. From what I can see SoftwareSerial is not supported by the ESP32 Arduino core due to issues with reliable bit timing due to the FreeRTOS base.

The build problem is possible to work around by removing `|| defined(ARDUINO_ARCH_ESP32)` from the list of supported platforms in the top of `LIN_master_portable/src/LIN_master_SoftwareSerial.cpp`.

**Comment by gicking** [comment]
Hi Dave,

there is an implementation of SoftwareSerial for ESP8266 and ESP32. You find it in the Arduino Library Manager (search for "ESPSoftwareSerial")

![grafik](https://github.com/gicking/LIN_master_portable_Arduino/assets/10261226/a09a5b14-9f74-440f-9d7d-b7a40952f906)

Alternatively you can download it from https://github.com/plerup/espsoftwareserial

HOWEVER, I'm surprised that this issue pops up when compiling LIN_**HardwareSerial**_ESP32_Background.ino. So let me check why this pulls in the SoftwareSerial library...

**Comment by gicking** [comment]
ah, you learn something new every day...

1) removed the `ESPSoftwareSerial` library -> compile fails, just as you describe
2) removed both `LIN_master_SoftwareSerial.*` files from the `LIN_master_portable_Arduino` library folder -> build successful
3) restored `ESPSoftwareSerial` library and `LIN_master_SoftwareSerial.*` files -> build successful

Seemingly each `*.c` file in a library's `src` folder is compiled, even when it's not required. I wasn't aware of that. 

I haven't checked it, but I suspect that this means you have to install the ESP32 and ESP8266 boards just to use the library with an Arduino Mega  :disappointed: 
**Update:** seems like I already covered that by adding `#ifdef(ARDUINO_ARCH_*)` at the top of the `*.c` files. But that doesn't help with uninstalled libraries

**Comment by davefiddes** [comment]
Yes. Arduino will compile everything in a library regardless of what the sketch pulls in. Given that there are 3 HW serial ports on the ESP32 I'd suggest dropping software serial support. You need C++17 support (ESP32 Arduino uses C++11) before you get the __has_include() macro you can use to test for the existence of a library.

**Comment by gicking** [comment]
darn!

Ok, changed as you proposed. I have updated the library to v1.2. You should be able to see it in the IDE library manager within a few hours. Alternatively just install manually from here

**Comment by davefiddes** [comment]
Thanks for fixing the problem, much appreciated. Thanks also for the great library. I'm using it to reverse engineer a Tesla oil pump and this is my first time working with LIN. Your library has been very helpful in understanding the protocol.
